name: CD Pipeline for HNG FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code

      - uses: actions/setup-python@v3
        name: Set up python
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install git -y

      - name: Deploy FastApi App
        uses: appleboy/ssh-action@v0.1.7        
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            if [ ! -d "/home/ubuntu/fastapi-hng" ]; then
              mkdir -p /home/ubuntu/fastapi-hng
            fi 
            cd /home/ubuntu/fastapi-hng
            if [ ! -d "fastapi-book-project-noah" ]; then
              git clone https://github.com/Noah-V/noah-fastapi-book-project
              cd fastapi-book-project-noah
            else
              cd fastapi-book-project-noah
            fi
            git pull origin main
            sudo apt-get install -y python3-venv
            python3 -m venv /home/ubuntu/fastapi-hng/fastapi-book-project-noah/venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            
            sudo tee /etc/systemd/system/fastapi-books.service << EOF
            [Unit]
            Description=FastAPI Book Project
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/home/ubuntu/fastapi-hng/fastapi-book-project-noah
            Environment="PATH=/home/ubuntu/fastapi-hng/fastapi-book-project-noah/venv/bin"
            ExecStart=/home/ubuntu/fastapi-hng/fastapi-book-project-noah/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000

            [Install]
            WantedBy=multi-user.target
            EOF

            # Reload systemd, enable and restart the service
            sudo systemctl daemon-reload
            sudo systemctl enable fastapi-books
            sudo systemctl restart fastapi-books
            
            # Restart nginx
            sudo nginx -t 
            sudo systemctl restart nginx
