name: CI PIPELINE FOR HNG FAST API

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest
      # - name: Start FastAPI server
      #   run: |
      #     source venv/bin/activate
      #     python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
      #     sleep 5
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest
